version: "3.7"
   
services:
  db:
    image: postgres
  
    environment:
     POSTGRES_PASSWORD: codex123!
      POSTGRES_DB: greetingsdb
      POSTGRES_USER: postgres 
 volumes:
  - ./pgdata:/var/lib/postgresql/data    
 ports:
      - "5432:5432"
web:
  image: b37c2a6c1506  
  depends_on:
  - db
  ports:
  -"4000:4000"
